apiVersion: v1
kind: Pod
spec:
  containers:
    - name: docker
      image: docker:dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: /certs
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
        - name: dind-certs
          mountPath: /certs
  volumes:
      - name: dind-storage
        emptyDir: {}
      - name: dind-certs
        emptyDir: {}