apiVersion: v1
kind: Pod
spec:
  containers:
    - name: docker
      image: docker:23.0.0-rc.4-dind-alpine3.17
      command: ["tail", "-f", "/dev/null"]
      imagePullPolicy: Always
  # volumes:
  #   - name: tf
  #     hostPath:
  #       path: /terraform