apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: psql
spec:
  serviceName: "db-service"
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
      - name: psql
        image: 085155013250.dkr.ecr.eu-central-1.amazonaws.com/rozsar-askmate:2
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: db-volume
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-volume
        persistentVolumeClaim:
          claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: psql
  ports:
  - port: 5432
    targetPort: 5432
    name: psql